logging.level: DEBUG
logging.level.sql: DEBUG
logging.level.ru.vtb.lead: DEBUG

logging:
  level:
    org:
      springframework:
        web: WARN
        hibernate: DEBUG
        jdbc:
          core: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      url: jdbc:h2:mem:default_db;DB_CLOSE_DELAY=-1;SCHEMA=PUBLIC

